import React from 'react'

const About = () => {
  return (
    <div style={{width:"70%",margin:"auto"}}>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi, adipisci quidem! Asperiores nobis nam, beatae pariatur quis ipsa soluta aspernatur impedit numquam, laborum exercitationem aut rerum blanditiis officiis deleniti amet libero nihil dolore ad ullam voluptates architecto facilis animi vel? Ipsum ex hic nemo repellat. Beatae expedita impedit laborum iure nesciunt excepturi dicta nemo, sit molestias, explicabo, eius ab. Voluptate quas molestias, sit sint quo debitis pariatur nisi quisquam ex, delectus soluta eveniet eaque deleniti recusandae similique, vitae magni? Nisi animi quia mollitia eos voluptatum expedita optio adipisci non esse et laudantium sapiente eligendi id, labore vero assumenda, eum nam. Quae possimus laboriosam earum ad quod aspernatur unde animi consequatur nostrum recusandae explicabo, molestias optio ut aliquid saepe incidunt libero veritatis corrupti esse ratione distinctio quidem deleniti! Quis accusamus explicabo, ipsam ad iste quibusdam enim quo amet quia nihil perferendis maxime et, repellendus repellat unde magni exercitationem neque mollitia nisi doloribus. Consectetur porro sequi dignissimos, eligendi tempore veritatis necessitatibus dolorem dolores, impedit voluptatum, odit accusantium sapiente repellendus. Ratione, veniam. Saepe odio sed quod aperiam nisi expedita eos doloribus quasi eveniet doloremque, incidunt vero adipisci suscipit officiis numquam magnam? Possimus quasi, quo unde quod molestias omnis minima nostrum ea quibusdam fugiat. Illum eum et laudantium dolorem excepturi optio, perspiciatis ipsum aut vel! Veniam, ea aperiam officiis vero perspiciatis ex aut molestiae, harum sit, mollitia facere ad itaque ratione blanditiis omnis neque nam quae provident porro? Fuga sint sit explicabo similique porro reprehenderit dicta quasi natus iusto qui sed, perferendis exercitationem placeat culpa. Accusamus tempore unde fuga suscipit non officia provident corrupti distinctio reprehenderit est. Eligendi autem soluta assumenda fuga commodi iusto magnam magni neque, ab quos eius officiis necessitatibus tempora asperiores culpa laboriosam in a quam quas aperiam explicabo. Officia nostrum sequi nesciunt suscipit aspernatur, ea optio qui id dolore labore!
    </div>
  )
}

export default About